#!/bin/bash
#PBS -A performance
#PBS -N nekrs_hang_standalone
#PBS -l walltime=01:00:00
#PBS -l select=700
#PBS -l place=scatter
#PBS -l filesystems=home:flare
#PBS -k doe
#PBS -j oe
export TZ='/usr/share/zoneinfo/US/Central'
cd $PBS_O_WORKDIR
echo Jobid: $PBS_JOBID
echo Running on host `hostname`
echo Running on nodes `cat $PBS_NODEFILE`
module load cmake
module load mpich/dbg
module list
export FI_CXI_RX_MATCH_MODE=hybrid
export UR_L0_USE_COPY_ENGINE=0
export MPIR_CVAR_DEBUG_PROGRESS_TIMEOUT=60
export SYCL_UR_USE_LEVEL_ZERO_V2=1
export PARRSB_VERBOSE_LEVEL=3
ulimit -c unlimited
export UR_L0_REUSE_DISCARDED_EVENTS=0
export UR_L0_DISABLE_EVENTS_CACHING=1
export SYCL_PI_LEVEL_ZERO_IMMEDIATE_COMMANDLISTS_EVENT_CLEANUP_THRESHOLD=-1
export SYCL_PI_LEVEL_ZERO_REUSE_DISCARDED_EVENTS=0
export ROMIO_HINTS=.romio_hint
export MPICH_MPIIO_STATS=1
export MPIR_CVAR_DEBUG_PROGRESS_TIMEOUT=60
export SYCL_UR_USE_LEVEL_ZERO_V2=1

# precompilation
date
# actual run
mpiexec --label --line-buffer -n 8400 -ppn 12 --cpu-bind=list:1-8:9-16:17-24:25-32:33-40:41-48:53-60:61-68:69-76:77-84:85-92:93-100 -- ./hang ./con.co2
